# Generated by Django 4.1.5 on 2023-01-14 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_medidor_mediciones'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estadisticas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumo_maximo', models.DecimalField(decimal_places=3, max_digits=6)),
                ('consumo_minimo', models.DecimalField(decimal_places=3, max_digits=6)),
                ('consumo_total', models.DecimalField(decimal_places=3, max_digits=6)),
                ('consumo_promedio', models.DecimalField(decimal_places=3, max_digits=6)),
            ],
        ),
    ]
