# Generated by Django 4.1.5 on 2023-01-14 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_estadisticas'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Estadisticas',
        ),
        migrations.AddField(
            model_name='medidor',
            name='consumo_total',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
            preserve_default=False,
        ),
    ]
