# Generated by Django 4.1.5 on 2023-01-15 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_delete_estadisticas_medidor_consumo_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicion',
            name='medidor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='mediciones', to='api.medidor'),
        ),
    ]
